deployment:
  tasks:
    - export DEPLOYPATH=/home/artsodev/files.1.1.4-artsodevalog.tech/
    - /bin/cp -R website/home $DEPLOYPATH
    - /bin/cp -R website/static_root $DEPLOYPATH
    - /bin/cp -R website/static $DEPLOYPATH
    - /bin/cp -R website/templates $DEPLOYPATH
    - /bin/cp -R website/website $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp website/manage.py $DEPLOYPATH