# Generated by Django 3.2 on 2021-07-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='isi',
            field=models.TextField(),
        ),
    ]
