# Generated by Django 3.2 on 2021-07-02 07:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_article_isi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='isi',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
