# Generated by Django 3.2 on 2021-08-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210820_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='snippets',
            new_name='snippet',
        ),
    ]
