# Generated by Django 3.2 on 2021-08-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_snippets_article_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
